name: Verify and Publish

on:
  push:
  workflow_dispatch:

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version-file: ".nvmrc"

      - name: Install dependencies
        run: npm ci

      - name: Typecheck
        run: npm run typecheck
      - name: ESLint
        run: npm run eslint
      - name: Prettier
        run: npm run prettier
      - name: depcheck
        run: npm run depcheck

      - name: Test
        env:
          EXPO_PUBLIC_PMO_API: ${{ vars.PMO_API }}
          EXPO_PUBLIC_PMO_ASSETS: ${{ vars.PMO_ASSETS }}
        run: npm run test

      # - name: Build Android
      #   env:
      #     EXPO_PUBLIC_PMO_API: ${{ vars.PMO_API }}
      #     EXPO_PUBLIC_PMO_ASSETS: ${{ vars.PMO_ASSETS }}
      #     EXPO_PUBLIC_GOOGLE_MAPS_API_KEY: ${{ secrets.GOOGLE_MAPS_API_KEY }}
      #     EXPO_PUBLIC_GOOGLE_OAUTH_CLIENT_ID: ${{ secrets.GOOGLE_OAUTH_CLIENT_ID }}
      #   run: npm run android:build
      # - name: Build iOS
      #   env:
      #     EXPO_PUBLIC_PMO_API: ${{ vars.PMO_API }}
      #     EXPO_PUBLIC_PMO_ASSETS: ${{ vars.PMO_ASSETS }}
      #     EXPO_PUBLIC_GOOGLE_MAPS_API_KEY: ${{ secrets.GOOGLE_MAPS_API_KEY }}
      #     EXPO_PUBLIC_GOOGLE_OAUTH_CLIENT_ID: ${{ secrets.GOOGLE_OAUTH_CLIENT_ID }}
      #   run: npm run ios:build
